package com.web.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CabinetExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public CabinetExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andResourceCodeIsNull() {
			addCriterion("resource_code is null");
			return (Criteria) this;
		}

		public Criteria andResourceCodeIsNotNull() {
			addCriterion("resource_code is not null");
			return (Criteria) this;
		}

		public Criteria andResourceCodeEqualTo(String value) {
			addCriterion("resource_code =", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeNotEqualTo(String value) {
			addCriterion("resource_code <>", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeGreaterThan(String value) {
			addCriterion("resource_code >", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeGreaterThanOrEqualTo(String value) {
			addCriterion("resource_code >=", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeLessThan(String value) {
			addCriterion("resource_code <", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeLessThanOrEqualTo(String value) {
			addCriterion("resource_code <=", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeLike(String value) {
			addCriterion("resource_code like", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeNotLike(String value) {
			addCriterion("resource_code not like", value, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeIn(List<String> values) {
			addCriterion("resource_code in", values, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeNotIn(List<String> values) {
			addCriterion("resource_code not in", values, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeBetween(String value1, String value2) {
			addCriterion("resource_code between", value1, value2, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andResourceCodeNotBetween(String value1, String value2) {
			addCriterion("resource_code not between", value1, value2, "resourceCode");
			return (Criteria) this;
		}

		public Criteria andRoomIdIsNull() {
			addCriterion("room_id is null");
			return (Criteria) this;
		}

		public Criteria andRoomIdIsNotNull() {
			addCriterion("room_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoomIdEqualTo(String value) {
			addCriterion("room_id =", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotEqualTo(String value) {
			addCriterion("room_id <>", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdGreaterThan(String value) {
			addCriterion("room_id >", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdGreaterThanOrEqualTo(String value) {
			addCriterion("room_id >=", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdLessThan(String value) {
			addCriterion("room_id <", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdLessThanOrEqualTo(String value) {
			addCriterion("room_id <=", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdLike(String value) {
			addCriterion("room_id like", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotLike(String value) {
			addCriterion("room_id not like", value, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdIn(List<String> values) {
			addCriterion("room_id in", values, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotIn(List<String> values) {
			addCriterion("room_id not in", values, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdBetween(String value1, String value2) {
			addCriterion("room_id between", value1, value2, "RoomId");
			return (Criteria) this;
		}

		public Criteria andRoomIdNotBetween(String value1, String value2) {
			addCriterion("room_id not between", value1, value2, "RoomId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdIsNull() {
			addCriterion("equipment_type_id is null");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdIsNotNull() {
			addCriterion("equipment_type_id is not null");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdEqualTo(String value) {
			addCriterion("equipment_type_id =", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdNotEqualTo(String value) {
			addCriterion("equipment_type_id <>", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdGreaterThan(String value) {
			addCriterion("equipment_type_id >", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("equipment_type_id >=", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdLessThan(String value) {
			addCriterion("equipment_type_id <", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdLessThanOrEqualTo(String value) {
			addCriterion("equipment_type_id <=", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdLike(String value) {
			addCriterion("equipment_type_id like", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdNotLike(String value) {
			addCriterion("equipment_type_id not like", value, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdIn(List<String> values) {
			addCriterion("equipment_type_id in", values, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdNotIn(List<String> values) {
			addCriterion("equipment_type_id not in", values, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdBetween(String value1, String value2) {
			addCriterion("equipment_type_id between", value1, value2, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andEquipmentTypeIdNotBetween(String value1, String value2) {
			addCriterion("equipment_type_id not between", value1, value2, "equipmentTypeId");
			return (Criteria) this;
		}

		public Criteria andAreaIdIsNull() {
			addCriterion("area_id is null");
			return (Criteria) this;
		}

		public Criteria andAreaIdIsNotNull() {
			addCriterion("area_id is not null");
			return (Criteria) this;
		}

		public Criteria andAreaIdEqualTo(String value) {
			addCriterion("area_id =", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdNotEqualTo(String value) {
			addCriterion("area_id <>", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdGreaterThan(String value) {
			addCriterion("area_id >", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
			addCriterion("area_id >=", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdLessThan(String value) {
			addCriterion("area_id <", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdLessThanOrEqualTo(String value) {
			addCriterion("area_id <=", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdLike(String value) {
			addCriterion("area_id like", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdNotLike(String value) {
			addCriterion("area_id not like", value, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdIn(List<String> values) {
			addCriterion("area_id in", values, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdNotIn(List<String> values) {
			addCriterion("area_id not in", values, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdBetween(String value1, String value2) {
			addCriterion("area_id between", value1, value2, "areaId");
			return (Criteria) this;
		}

		public Criteria andAreaIdNotBetween(String value1, String value2) {
			addCriterion("area_id not between", value1, value2, "areaId");
			return (Criteria) this;
		}

		public Criteria andXIsNull() {
			addCriterion("x is null");
			return (Criteria) this;
		}

		public Criteria andXIsNotNull() {
			addCriterion("x is not null");
			return (Criteria) this;
		}

		public Criteria andXEqualTo(Float value) {
			addCriterion("x =", value, "x");
			return (Criteria) this;
		}

		public Criteria andXNotEqualTo(Float value) {
			addCriterion("x <>", value, "x");
			return (Criteria) this;
		}

		public Criteria andXGreaterThan(Float value) {
			addCriterion("x >", value, "x");
			return (Criteria) this;
		}

		public Criteria andXGreaterThanOrEqualTo(Float value) {
			addCriterion("x >=", value, "x");
			return (Criteria) this;
		}

		public Criteria andXLessThan(Float value) {
			addCriterion("x <", value, "x");
			return (Criteria) this;
		}

		public Criteria andXLessThanOrEqualTo(Float value) {
			addCriterion("x <=", value, "x");
			return (Criteria) this;
		}

		public Criteria andXIn(List<Float> values) {
			addCriterion("x in", values, "x");
			return (Criteria) this;
		}

		public Criteria andXNotIn(List<Float> values) {
			addCriterion("x not in", values, "x");
			return (Criteria) this;
		}

		public Criteria andXBetween(Float value1, Float value2) {
			addCriterion("x between", value1, value2, "x");
			return (Criteria) this;
		}

		public Criteria andXNotBetween(Float value1, Float value2) {
			addCriterion("x not between", value1, value2, "x");
			return (Criteria) this;
		}

		public Criteria andYIsNull() {
			addCriterion("y is null");
			return (Criteria) this;
		}

		public Criteria andYIsNotNull() {
			addCriterion("y is not null");
			return (Criteria) this;
		}

		public Criteria andYEqualTo(Float value) {
			addCriterion("y =", value, "y");
			return (Criteria) this;
		}

		public Criteria andYNotEqualTo(Float value) {
			addCriterion("y <>", value, "y");
			return (Criteria) this;
		}

		public Criteria andYGreaterThan(Float value) {
			addCriterion("y >", value, "y");
			return (Criteria) this;
		}

		public Criteria andYGreaterThanOrEqualTo(Float value) {
			addCriterion("y >=", value, "y");
			return (Criteria) this;
		}

		public Criteria andYLessThan(Float value) {
			addCriterion("y <", value, "y");
			return (Criteria) this;
		}

		public Criteria andYLessThanOrEqualTo(Float value) {
			addCriterion("y <=", value, "y");
			return (Criteria) this;
		}

		public Criteria andYIn(List<Float> values) {
			addCriterion("y in", values, "y");
			return (Criteria) this;
		}

		public Criteria andYNotIn(List<Float> values) {
			addCriterion("y not in", values, "y");
			return (Criteria) this;
		}

		public Criteria andYBetween(Float value1, Float value2) {
			addCriterion("y between", value1, value2, "y");
			return (Criteria) this;
		}

		public Criteria andYNotBetween(Float value1, Float value2) {
			addCriterion("y not between", value1, value2, "y");
			return (Criteria) this;
		}

		public Criteria andZIsNull() {
			addCriterion("z is null");
			return (Criteria) this;
		}

		public Criteria andZIsNotNull() {
			addCriterion("z is not null");
			return (Criteria) this;
		}

		public Criteria andZEqualTo(Float value) {
			addCriterion("z =", value, "z");
			return (Criteria) this;
		}

		public Criteria andZNotEqualTo(Float value) {
			addCriterion("z <>", value, "z");
			return (Criteria) this;
		}

		public Criteria andZGreaterThan(Float value) {
			addCriterion("z >", value, "z");
			return (Criteria) this;
		}

		public Criteria andZGreaterThanOrEqualTo(Float value) {
			addCriterion("z >=", value, "z");
			return (Criteria) this;
		}

		public Criteria andZLessThan(Float value) {
			addCriterion("z <", value, "z");
			return (Criteria) this;
		}

		public Criteria andZLessThanOrEqualTo(Float value) {
			addCriterion("z <=", value, "z");
			return (Criteria) this;
		}

		public Criteria andZIn(List<Float> values) {
			addCriterion("z in", values, "z");
			return (Criteria) this;
		}

		public Criteria andZNotIn(List<Float> values) {
			addCriterion("z not in", values, "z");
			return (Criteria) this;
		}

		public Criteria andZBetween(Float value1, Float value2) {
			addCriterion("z between", value1, value2, "z");
			return (Criteria) this;
		}

		public Criteria andZNotBetween(Float value1, Float value2) {
			addCriterion("z not between", value1, value2, "z");
			return (Criteria) this;
		}

		public Criteria andHeightIsNull() {
			addCriterion("height is null");
			return (Criteria) this;
		}

		public Criteria andHeightIsNotNull() {
			addCriterion("height is not null");
			return (Criteria) this;
		}

		public Criteria andHeightEqualTo(Integer value) {
			addCriterion("height =", value, "height");
			return (Criteria) this;
		}

		public Criteria andHeightNotEqualTo(Integer value) {
			addCriterion("height <>", value, "height");
			return (Criteria) this;
		}

		public Criteria andHeightGreaterThan(Integer value) {
			addCriterion("height >", value, "height");
			return (Criteria) this;
		}

		public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("height >=", value, "height");
			return (Criteria) this;
		}

		public Criteria andHeightLessThan(Integer value) {
			addCriterion("height <", value, "height");
			return (Criteria) this;
		}

		public Criteria andHeightLessThanOrEqualTo(Integer value) {
			addCriterion("height <=", value, "height");
			return (Criteria) this;
		}

		public Criteria andHeightIn(List<Integer> values) {
			addCriterion("height in", values, "height");
			return (Criteria) this;
		}

		public Criteria andHeightNotIn(List<Integer> values) {
			addCriterion("height not in", values, "height");
			return (Criteria) this;
		}

		public Criteria andHeightBetween(Integer value1, Integer value2) {
			addCriterion("height between", value1, value2, "height");
			return (Criteria) this;
		}

		public Criteria andHeightNotBetween(Integer value1, Integer value2) {
			addCriterion("height not between", value1, value2, "height");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("weight is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("weight is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Float value) {
			addCriterion("weight =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Float value) {
			addCriterion("weight <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Float value) {
			addCriterion("weight >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Float value) {
			addCriterion("weight >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Float value) {
			addCriterion("weight <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Float value) {
			addCriterion("weight <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Float> values) {
			addCriterion("weight in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Float> values) {
			addCriterion("weight not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Float value1, Float value2) {
			addCriterion("weight between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Float value1, Float value2) {
			addCriterion("weight not between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andPowerIsNull() {
			addCriterion("power is null");
			return (Criteria) this;
		}

		public Criteria andPowerIsNotNull() {
			addCriterion("power is not null");
			return (Criteria) this;
		}

		public Criteria andPowerEqualTo(Float value) {
			addCriterion("power =", value, "power");
			return (Criteria) this;
		}

		public Criteria andPowerNotEqualTo(Float value) {
			addCriterion("power <>", value, "power");
			return (Criteria) this;
		}

		public Criteria andPowerGreaterThan(Float value) {
			addCriterion("power >", value, "power");
			return (Criteria) this;
		}

		public Criteria andPowerGreaterThanOrEqualTo(Float value) {
			addCriterion("power >=", value, "power");
			return (Criteria) this;
		}

		public Criteria andPowerLessThan(Float value) {
			addCriterion("power <", value, "power");
			return (Criteria) this;
		}

		public Criteria andPowerLessThanOrEqualTo(Float value) {
			addCriterion("power <=", value, "power");
			return (Criteria) this;
		}

		public Criteria andPowerIn(List<Float> values) {
			addCriterion("power in", values, "power");
			return (Criteria) this;
		}

		public Criteria andPowerNotIn(List<Float> values) {
			addCriterion("power not in", values, "power");
			return (Criteria) this;
		}

		public Criteria andPowerBetween(Float value1, Float value2) {
			addCriterion("power between", value1, value2, "power");
			return (Criteria) this;
		}

		public Criteria andPowerNotBetween(Float value1, Float value2) {
			addCriterion("power not between", value1, value2, "power");
			return (Criteria) this;
		}

		public Criteria andRoomStatusIsNull() {
			addCriterion("room_status is null");
			return (Criteria) this;
		}

		public Criteria andRoomStatusIsNotNull() {
			addCriterion("room_status is not null");
			return (Criteria) this;
		}

		public Criteria andRoomStatusEqualTo(Integer value) {
			addCriterion("room_status =", value, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusNotEqualTo(Integer value) {
			addCriterion("room_status <>", value, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusGreaterThan(Integer value) {
			addCriterion("room_status >", value, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("room_status >=", value, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusLessThan(Integer value) {
			addCriterion("room_status <", value, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusLessThanOrEqualTo(Integer value) {
			addCriterion("room_status <=", value, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusIn(List<Integer> values) {
			addCriterion("room_status in", values, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusNotIn(List<Integer> values) {
			addCriterion("room_status not in", values, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusBetween(Integer value1, Integer value2) {
			addCriterion("room_status between", value1, value2, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andRoomStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("room_status not between", value1, value2, "roomStatus");
			return (Criteria) this;
		}

		public Criteria andModelHeightIsNull() {
			addCriterion("model_height is null");
			return (Criteria) this;
		}

		public Criteria andModelHeightIsNotNull() {
			addCriterion("model_height is not null");
			return (Criteria) this;
		}

		public Criteria andModelHeightEqualTo(Integer value) {
			addCriterion("model_height =", value, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightNotEqualTo(Integer value) {
			addCriterion("model_height <>", value, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightGreaterThan(Integer value) {
			addCriterion("model_height >", value, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("model_height >=", value, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightLessThan(Integer value) {
			addCriterion("model_height <", value, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightLessThanOrEqualTo(Integer value) {
			addCriterion("model_height <=", value, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightIn(List<Integer> values) {
			addCriterion("model_height in", values, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightNotIn(List<Integer> values) {
			addCriterion("model_height not in", values, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightBetween(Integer value1, Integer value2) {
			addCriterion("model_height between", value1, value2, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelHeightNotBetween(Integer value1, Integer value2) {
			addCriterion("model_height not between", value1, value2, "modelHeight");
			return (Criteria) this;
		}

		public Criteria andModelWidthIsNull() {
			addCriterion("model_width is null");
			return (Criteria) this;
		}

		public Criteria andModelWidthIsNotNull() {
			addCriterion("model_width is not null");
			return (Criteria) this;
		}

		public Criteria andModelWidthEqualTo(Integer value) {
			addCriterion("model_width =", value, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthNotEqualTo(Integer value) {
			addCriterion("model_width <>", value, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthGreaterThan(Integer value) {
			addCriterion("model_width >", value, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthGreaterThanOrEqualTo(Integer value) {
			addCriterion("model_width >=", value, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthLessThan(Integer value) {
			addCriterion("model_width <", value, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthLessThanOrEqualTo(Integer value) {
			addCriterion("model_width <=", value, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthIn(List<Integer> values) {
			addCriterion("model_width in", values, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthNotIn(List<Integer> values) {
			addCriterion("model_width not in", values, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthBetween(Integer value1, Integer value2) {
			addCriterion("model_width between", value1, value2, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelWidthNotBetween(Integer value1, Integer value2) {
			addCriterion("model_width not between", value1, value2, "modelWidth");
			return (Criteria) this;
		}

		public Criteria andModelColorIsNull() {
			addCriterion("model_color is null");
			return (Criteria) this;
		}

		public Criteria andModelColorIsNotNull() {
			addCriterion("model_color is not null");
			return (Criteria) this;
		}

		public Criteria andModelColorEqualTo(String value) {
			addCriterion("model_color =", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorNotEqualTo(String value) {
			addCriterion("model_color <>", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorGreaterThan(String value) {
			addCriterion("model_color >", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorGreaterThanOrEqualTo(String value) {
			addCriterion("model_color >=", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorLessThan(String value) {
			addCriterion("model_color <", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorLessThanOrEqualTo(String value) {
			addCriterion("model_color <=", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorLike(String value) {
			addCriterion("model_color like", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorNotLike(String value) {
			addCriterion("model_color not like", value, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorIn(List<String> values) {
			addCriterion("model_color in", values, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorNotIn(List<String> values) {
			addCriterion("model_color not in", values, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorBetween(String value1, String value2) {
			addCriterion("model_color between", value1, value2, "modelColor");
			return (Criteria) this;
		}

		public Criteria andModelColorNotBetween(String value1, String value2) {
			addCriterion("model_color not between", value1, value2, "modelColor");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeIsNull() {
			addCriterion("warranty_time is null");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeIsNotNull() {
			addCriterion("warranty_time is not null");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeEqualTo(Date value) {
			addCriterion("warranty_time =", value, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeNotEqualTo(Date value) {
			addCriterion("warranty_time <>", value, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeGreaterThan(Date value) {
			addCriterion("warranty_time >", value, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("warranty_time >=", value, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeLessThan(Date value) {
			addCriterion("warranty_time <", value, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeLessThanOrEqualTo(Date value) {
			addCriterion("warranty_time <=", value, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeIn(List<Date> values) {
			addCriterion("warranty_time in", values, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeNotIn(List<Date> values) {
			addCriterion("warranty_time not in", values, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeBetween(Date value1, Date value2) {
			addCriterion("warranty_time between", value1, value2, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWarrantyTimeNotBetween(Date value1, Date value2) {
			addCriterion("warranty_time not between", value1, value2, "warrantyTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeIsNull() {
			addCriterion("work_time is null");
			return (Criteria) this;
		}

		public Criteria andWorkTimeIsNotNull() {
			addCriterion("work_time is not null");
			return (Criteria) this;
		}

		public Criteria andWorkTimeEqualTo(Date value) {
			addCriterion("work_time =", value, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeNotEqualTo(Date value) {
			addCriterion("work_time <>", value, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeGreaterThan(Date value) {
			addCriterion("work_time >", value, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("work_time >=", value, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeLessThan(Date value) {
			addCriterion("work_time <", value, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeLessThanOrEqualTo(Date value) {
			addCriterion("work_time <=", value, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeIn(List<Date> values) {
			addCriterion("work_time in", values, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeNotIn(List<Date> values) {
			addCriterion("work_time not in", values, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeBetween(Date value1, Date value2) {
			addCriterion("work_time between", value1, value2, "workTime");
			return (Criteria) this;
		}

		public Criteria andWorkTimeNotBetween(Date value1, Date value2) {
			addCriterion("work_time not between", value1, value2, "workTime");
			return (Criteria) this;
		}

		public Criteria andUOrderIsNull() {
			addCriterion("u_order is null");
			return (Criteria) this;
		}

		public Criteria andUOrderIsNotNull() {
			addCriterion("u_order is not null");
			return (Criteria) this;
		}

		public Criteria andUOrderEqualTo(Integer value) {
			addCriterion("u_order =", value, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderNotEqualTo(Integer value) {
			addCriterion("u_order <>", value, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderGreaterThan(Integer value) {
			addCriterion("u_order >", value, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_order >=", value, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderLessThan(Integer value) {
			addCriterion("u_order <", value, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderLessThanOrEqualTo(Integer value) {
			addCriterion("u_order <=", value, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderIn(List<Integer> values) {
			addCriterion("u_order in", values, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderNotIn(List<Integer> values) {
			addCriterion("u_order not in", values, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderBetween(Integer value1, Integer value2) {
			addCriterion("u_order between", value1, value2, "uOrder");
			return (Criteria) this;
		}

		public Criteria andUOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("u_order not between", value1, value2, "uOrder");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateNameIsNull() {
			addCriterion("create_name is null");
			return (Criteria) this;
		}

		public Criteria andCreateNameIsNotNull() {
			addCriterion("create_name is not null");
			return (Criteria) this;
		}

		public Criteria andCreateNameEqualTo(String value) {
			addCriterion("create_name =", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameNotEqualTo(String value) {
			addCriterion("create_name <>", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameGreaterThan(String value) {
			addCriterion("create_name >", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
			addCriterion("create_name >=", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameLessThan(String value) {
			addCriterion("create_name <", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameLessThanOrEqualTo(String value) {
			addCriterion("create_name <=", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameLike(String value) {
			addCriterion("create_name like", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameNotLike(String value) {
			addCriterion("create_name not like", value, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameIn(List<String> values) {
			addCriterion("create_name in", values, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameNotIn(List<String> values) {
			addCriterion("create_name not in", values, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameBetween(String value1, String value2) {
			addCriterion("create_name between", value1, value2, "createName");
			return (Criteria) this;
		}

		public Criteria andCreateNameNotBetween(String value1, String value2) {
			addCriterion("create_name not between", value1, value2, "createName");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIsNull() {
			addCriterion("update_name is null");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIsNotNull() {
			addCriterion("update_name is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateNameEqualTo(String value) {
			addCriterion("update_name =", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotEqualTo(String value) {
			addCriterion("update_name <>", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameGreaterThan(String value) {
			addCriterion("update_name >", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
			addCriterion("update_name >=", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLessThan(String value) {
			addCriterion("update_name <", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLessThanOrEqualTo(String value) {
			addCriterion("update_name <=", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLike(String value) {
			addCriterion("update_name like", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotLike(String value) {
			addCriterion("update_name not like", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIn(List<String> values) {
			addCriterion("update_name in", values, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotIn(List<String> values) {
			addCriterion("update_name not in", values, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameBetween(String value1, String value2) {
			addCriterion("update_name between", value1, value2, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotBetween(String value1, String value2) {
			addCriterion("update_name not between", value1, value2, "updateName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table t_b_cabinet
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table t_b_cabinet
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}