package com.web.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author 田军兴
 * @date 2016-06-29
 */
public class OperLogExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public OperLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIsNull() {
			addCriterion("device_name is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIsNotNull() {
			addCriterion("device_name is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNameEqualTo(String value) {
			addCriterion("device_name =", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotEqualTo(String value) {
			addCriterion("device_name <>", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameGreaterThan(String value) {
			addCriterion("device_name >", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
			addCriterion("device_name >=", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLessThan(String value) {
			addCriterion("device_name <", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLessThanOrEqualTo(String value) {
			addCriterion("device_name <=", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLike(String value) {
			addCriterion("device_name like", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotLike(String value) {
			addCriterion("device_name not like", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIn(List<String> values) {
			addCriterion("device_name in", values, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotIn(List<String> values) {
			addCriterion("device_name not in", values, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameBetween(String value1, String value2) {
			addCriterion("device_name between", value1, value2, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotBetween(String value1, String value2) {
			addCriterion("device_name not between", value1, value2, "deviceName");
			return (Criteria) this;
		}

		public Criteria andOperTypeIsNull() {
			addCriterion("oper_type is null");
			return (Criteria) this;
		}

		public Criteria andOperTypeIsNotNull() {
			addCriterion("oper_type is not null");
			return (Criteria) this;
		}

		public Criteria andOperTypeEqualTo(String value) {
			addCriterion("oper_type =", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeNotEqualTo(String value) {
			addCriterion("oper_type <>", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeGreaterThan(String value) {
			addCriterion("oper_type >", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeGreaterThanOrEqualTo(String value) {
			addCriterion("oper_type >=", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeLessThan(String value) {
			addCriterion("oper_type <", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeLessThanOrEqualTo(String value) {
			addCriterion("oper_type <=", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeLike(String value) {
			addCriterion("oper_type like", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeNotLike(String value) {
			addCriterion("oper_type not like", value, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeIn(List<String> values) {
			addCriterion("oper_type in", values, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeNotIn(List<String> values) {
			addCriterion("oper_type not in", values, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeBetween(String value1, String value2) {
			addCriterion("oper_type between", value1, value2, "operType");
			return (Criteria) this;
		}

		public Criteria andOperTypeNotBetween(String value1, String value2) {
			addCriterion("oper_type not between", value1, value2, "operType");
			return (Criteria) this;
		}

		public Criteria andLogLevelIsNull() {
			addCriterion("log_level is null");
			return (Criteria) this;
		}

		public Criteria andLogLevelIsNotNull() {
			addCriterion("log_level is not null");
			return (Criteria) this;
		}

		public Criteria andLogLevelEqualTo(Integer value) {
			addCriterion("log_level =", value, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelNotEqualTo(Integer value) {
			addCriterion("log_level <>", value, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelGreaterThan(Integer value) {
			addCriterion("log_level >", value, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("log_level >=", value, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelLessThan(Integer value) {
			addCriterion("log_level <", value, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelLessThanOrEqualTo(Integer value) {
			addCriterion("log_level <=", value, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelIn(List<Integer> values) {
			addCriterion("log_level in", values, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelNotIn(List<Integer> values) {
			addCriterion("log_level not in", values, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelBetween(Integer value1, Integer value2) {
			addCriterion("log_level between", value1, value2, "logLevel");
			return (Criteria) this;
		}

		public Criteria andLogLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("log_level not between", value1, value2, "logLevel");
			return (Criteria) this;
		}

		public Criteria andActionTypeIsNull() {
			addCriterion("action_type is null");
			return (Criteria) this;
		}

		public Criteria andActionTypeIsNotNull() {
			addCriterion("action_type is not null");
			return (Criteria) this;
		}

		public Criteria andActionTypeEqualTo(String value) {
			addCriterion("action_type =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(String value) {
			addCriterion("action_type <>", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeGreaterThan(String value) {
			addCriterion("action_type >", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeGreaterThanOrEqualTo(String value) {
			addCriterion("action_type >=", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeLessThan(String value) {
			addCriterion("action_type <", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeLessThanOrEqualTo(String value) {
			addCriterion("action_type <=", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeLike(String value) {
			addCriterion("action_type like", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeNotLike(String value) {
			addCriterion("action_type not like", value, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeIn(List<String> values) {
			addCriterion("action_type in", values, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeNotIn(List<String> values) {
			addCriterion("action_type not in", values, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeBetween(String value1, String value2) {
			addCriterion("action_type between", value1, value2, "actionType");
			return (Criteria) this;
		}

		public Criteria andActionTypeNotBetween(String value1, String value2) {
			addCriterion("action_type not between", value1, value2, "actionType");
			return (Criteria) this;
		}

		public Criteria andOperPropIsNull() {
			addCriterion("oper_prop is null");
			return (Criteria) this;
		}

		public Criteria andOperPropIsNotNull() {
			addCriterion("oper_prop is not null");
			return (Criteria) this;
		}

		public Criteria andOperPropEqualTo(String value) {
			addCriterion("oper_prop =", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropNotEqualTo(String value) {
			addCriterion("oper_prop <>", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropGreaterThan(String value) {
			addCriterion("oper_prop >", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropGreaterThanOrEqualTo(String value) {
			addCriterion("oper_prop >=", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropLessThan(String value) {
			addCriterion("oper_prop <", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropLessThanOrEqualTo(String value) {
			addCriterion("oper_prop <=", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropLike(String value) {
			addCriterion("oper_prop like", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropNotLike(String value) {
			addCriterion("oper_prop not like", value, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropIn(List<String> values) {
			addCriterion("oper_prop in", values, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropNotIn(List<String> values) {
			addCriterion("oper_prop not in", values, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropBetween(String value1, String value2) {
			addCriterion("oper_prop between", value1, value2, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperPropNotBetween(String value1, String value2) {
			addCriterion("oper_prop not between", value1, value2, "operProp");
			return (Criteria) this;
		}

		public Criteria andOperUserIdIsNull() {
			addCriterion("oper_user_id is null");
			return (Criteria) this;
		}

		public Criteria andOperUserIdIsNotNull() {
			addCriterion("oper_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andOperUserIdEqualTo(String value) {
			addCriterion("oper_user_id =", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdNotEqualTo(String value) {
			addCriterion("oper_user_id <>", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdGreaterThan(String value) {
			addCriterion("oper_user_id >", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("oper_user_id >=", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdLessThan(String value) {
			addCriterion("oper_user_id <", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdLessThanOrEqualTo(String value) {
			addCriterion("oper_user_id <=", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdLike(String value) {
			addCriterion("oper_user_id like", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdNotLike(String value) {
			addCriterion("oper_user_id not like", value, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdIn(List<String> values) {
			addCriterion("oper_user_id in", values, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdNotIn(List<String> values) {
			addCriterion("oper_user_id not in", values, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdBetween(String value1, String value2) {
			addCriterion("oper_user_id between", value1, value2, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserIdNotBetween(String value1, String value2) {
			addCriterion("oper_user_id not between", value1, value2, "operUserId");
			return (Criteria) this;
		}

		public Criteria andOperUserNameIsNull() {
			addCriterion("oper_user_name is null");
			return (Criteria) this;
		}

		public Criteria andOperUserNameIsNotNull() {
			addCriterion("oper_user_name is not null");
			return (Criteria) this;
		}

		public Criteria andOperUserNameEqualTo(String value) {
			addCriterion("oper_user_name =", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameNotEqualTo(String value) {
			addCriterion("oper_user_name <>", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameGreaterThan(String value) {
			addCriterion("oper_user_name >", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("oper_user_name >=", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameLessThan(String value) {
			addCriterion("oper_user_name <", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameLessThanOrEqualTo(String value) {
			addCriterion("oper_user_name <=", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameLike(String value) {
			addCriterion("oper_user_name like", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameNotLike(String value) {
			addCriterion("oper_user_name not like", value, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameIn(List<String> values) {
			addCriterion("oper_user_name in", values, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameNotIn(List<String> values) {
			addCriterion("oper_user_name not in", values, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameBetween(String value1, String value2) {
			addCriterion("oper_user_name between", value1, value2, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperUserNameNotBetween(String value1, String value2) {
			addCriterion("oper_user_name not between", value1, value2, "operUserName");
			return (Criteria) this;
		}

		public Criteria andOperDateIsNull() {
			addCriterion("oper_date is null");
			return (Criteria) this;
		}

		public Criteria andOperDateIsNotNull() {
			addCriterion("oper_date is not null");
			return (Criteria) this;
		}

		public Criteria andOperDateEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date =", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date <>", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateGreaterThan(Date value) {
			addCriterionForJDBCDate("oper_date >", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date >=", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateLessThan(Date value) {
			addCriterionForJDBCDate("oper_date <", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date <=", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateIn(List<Date> values) {
			addCriterionForJDBCDate("oper_date in", values, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("oper_date not in", values, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("oper_date between", value1, value2, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("oper_date not between", value1, value2, "operDate");
			return (Criteria) this;
		}

		public Criteria andCommentsIsNull() {
			addCriterion("comments is null");
			return (Criteria) this;
		}

		public Criteria andCommentsIsNotNull() {
			addCriterion("comments is not null");
			return (Criteria) this;
		}

		public Criteria andCommentsEqualTo(String value) {
			addCriterion("comments =", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsNotEqualTo(String value) {
			addCriterion("comments <>", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsGreaterThan(String value) {
			addCriterion("comments >", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsGreaterThanOrEqualTo(String value) {
			addCriterion("comments >=", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsLessThan(String value) {
			addCriterion("comments <", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsLessThanOrEqualTo(String value) {
			addCriterion("comments <=", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsLike(String value) {
			addCriterion("comments like", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsNotLike(String value) {
			addCriterion("comments not like", value, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsIn(List<String> values) {
			addCriterion("comments in", values, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsNotIn(List<String> values) {
			addCriterion("comments not in", values, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsBetween(String value1, String value2) {
			addCriterion("comments between", value1, value2, "comments");
			return (Criteria) this;
		}

		public Criteria andCommentsNotBetween(String value1, String value2) {
			addCriterion("comments not between", value1, value2, "comments");
			return (Criteria) this;
		}

		public Criteria andLogTypeEqualTo(Integer value) {
			addCriterion("log_type =", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotEqualTo(Integer value) {
			addCriterion("log_type <>", value, "logType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}