package com.web.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author 田军兴
 * @date 2016-06-29
 */
public class OperLogExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected List<OperLogExample.Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public OperLogExample() {
		oredCriteria = new ArrayList<OperLogExample.Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public List<OperLogExample.Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void or(OperLogExample.Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public OperLogExample.Criteria or() {
		OperLogExample.Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public OperLogExample.Criteria createCriteria() {
		OperLogExample.Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected OperLogExample.Criteria createCriteriaInternal() {
		OperLogExample.Criteria criteria = new OperLogExample.Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<OperLogExample.Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<OperLogExample.Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<OperLogExample.Criterion> getAllCriteria() {
			return criteria;
		}

		public List<OperLogExample.Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new OperLogExample.Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new OperLogExample.Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new OperLogExample.Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public OperLogExample.Criteria andIdIsNull() {
			addCriterion("id is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameIsNull() {
			addCriterion("device_name is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameIsNotNull() {
			addCriterion("device_name is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameEqualTo(String value) {
			addCriterion("device_name =", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameNotEqualTo(String value) {
			addCriterion("device_name <>", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameGreaterThan(String value) {
			addCriterion("device_name >", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
			addCriterion("device_name >=", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameLessThan(String value) {
			addCriterion("device_name <", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameLessThanOrEqualTo(String value) {
			addCriterion("device_name <=", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameLike(String value) {
			addCriterion("device_name like", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameNotLike(String value) {
			addCriterion("device_name not like", value, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameIn(List<String> values) {
			addCriterion("device_name in", values, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameNotIn(List<String> values) {
			addCriterion("device_name not in", values, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameBetween(String value1, String value2) {
			addCriterion("device_name between", value1, value2, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andDeviceNameNotBetween(String value1, String value2) {
			addCriterion("device_name not between", value1, value2, "deviceName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeIsNull() {
			addCriterion("oper_type is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeIsNotNull() {
			addCriterion("oper_type is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeEqualTo(String value) {
			addCriterion("oper_type =", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeNotEqualTo(String value) {
			addCriterion("oper_type <>", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeGreaterThan(String value) {
			addCriterion("oper_type >", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeGreaterThanOrEqualTo(String value) {
			addCriterion("oper_type >=", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeLessThan(String value) {
			addCriterion("oper_type <", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeLessThanOrEqualTo(String value) {
			addCriterion("oper_type <=", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeLike(String value) {
			addCriterion("oper_type like", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeNotLike(String value) {
			addCriterion("oper_type not like", value, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeIn(List<String> values) {
			addCriterion("oper_type in", values, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeNotIn(List<String> values) {
			addCriterion("oper_type not in", values, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeBetween(String value1, String value2) {
			addCriterion("oper_type between", value1, value2, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperTypeNotBetween(String value1, String value2) {
			addCriterion("oper_type not between", value1, value2, "operType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelIsNull() {
			addCriterion("log_level is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelIsNotNull() {
			addCriterion("log_level is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelEqualTo(Integer value) {
			addCriterion("log_level =", value, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelNotEqualTo(Integer value) {
			addCriterion("log_level <>", value, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelGreaterThan(Integer value) {
			addCriterion("log_level >", value, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("log_level >=", value, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelLessThan(Integer value) {
			addCriterion("log_level <", value, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelLessThanOrEqualTo(Integer value) {
			addCriterion("log_level <=", value, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelIn(List<Integer> values) {
			addCriterion("log_level in", values, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelNotIn(List<Integer> values) {
			addCriterion("log_level not in", values, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelBetween(Integer value1, Integer value2) {
			addCriterion("log_level between", value1, value2, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("log_level not between", value1, value2, "logLevel");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeIsNull() {
			addCriterion("action_type is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeIsNotNull() {
			addCriterion("action_type is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeEqualTo(String value) {
			addCriterion("action_type =", value, "action");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionNotEqualTo(String value) {
			addCriterion("action_type <>", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeGreaterThan(String value) {
			addCriterion("action_type >", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeGreaterThanOrEqualTo(String value) {
			addCriterion("action_type >=", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeLessThan(String value) {
			addCriterion("action_type <", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeLessThanOrEqualTo(String value) {
			addCriterion("action_type <=", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeLike(String value) {
			addCriterion("action_type like", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeNotLike(String value) {
			addCriterion("action_type not like", value, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeIn(List<String> values) {
			addCriterion("action_type in", values, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeNotIn(List<String> values) {
			addCriterion("action_type not in", values, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeBetween(String value1, String value2) {
			addCriterion("action_type between", value1, value2, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andActionTypeNotBetween(String value1, String value2) {
			addCriterion("action_type not between", value1, value2, "actionType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropIsNull() {
			addCriterion("oper_prop is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropIsNotNull() {
			addCriterion("oper_prop is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropEqualTo(String value) {
			addCriterion("oper_prop =", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropNotEqualTo(String value) {
			addCriterion("oper_prop <>", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropGreaterThan(String value) {
			addCriterion("oper_prop >", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropGreaterThanOrEqualTo(String value) {
			addCriterion("oper_prop >=", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropLessThan(String value) {
			addCriterion("oper_prop <", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropLessThanOrEqualTo(String value) {
			addCriterion("oper_prop <=", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropLike(String value) {
			addCriterion("oper_prop like", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropNotLike(String value) {
			addCriterion("oper_prop not like", value, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropIn(List<String> values) {
			addCriterion("oper_prop in", values, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropNotIn(List<String> values) {
			addCriterion("oper_prop not in", values, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropBetween(String value1, String value2) {
			addCriterion("oper_prop between", value1, value2, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperPropNotBetween(String value1, String value2) {
			addCriterion("oper_prop not between", value1, value2, "operProp");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdIsNull() {
			addCriterion("oper_user_id is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdIsNotNull() {
			addCriterion("oper_user_id is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdEqualTo(String value) {
			addCriterion("oper_user_id =", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdNotEqualTo(String value) {
			addCriterion("oper_user_id <>", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdGreaterThan(String value) {
			addCriterion("oper_user_id >", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("oper_user_id >=", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdLessThan(String value) {
			addCriterion("oper_user_id <", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdLessThanOrEqualTo(String value) {
			addCriterion("oper_user_id <=", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdLike(String value) {
			addCriterion("oper_user_id like", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdNotLike(String value) {
			addCriterion("oper_user_id not like", value, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdIn(List<String> values) {
			addCriterion("oper_user_id in", values, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdNotIn(List<String> values) {
			addCriterion("oper_user_id not in", values, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdBetween(String value1, String value2) {
			addCriterion("oper_user_id between", value1, value2, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserIdNotBetween(String value1, String value2) {
			addCriterion("oper_user_id not between", value1, value2, "operUserId");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameIsNull() {
			addCriterion("oper_user_name is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameIsNotNull() {
			addCriterion("oper_user_name is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameEqualTo(String value) {
			addCriterion("oper_user_name =", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameNotEqualTo(String value) {
			addCriterion("oper_user_name <>", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameGreaterThan(String value) {
			addCriterion("oper_user_name >", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("oper_user_name >=", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameLessThan(String value) {
			addCriterion("oper_user_name <", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameLessThanOrEqualTo(String value) {
			addCriterion("oper_user_name <=", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameLike(String value) {
			addCriterion("oper_user_name like", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameNotLike(String value) {
			addCriterion("oper_user_name not like", value, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameIn(List<String> values) {
			addCriterion("oper_user_name in", values, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameNotIn(List<String> values) {
			addCriterion("oper_user_name not in", values, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameBetween(String value1, String value2) {
			addCriterion("oper_user_name between", value1, value2, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperUserNameNotBetween(String value1, String value2) {
			addCriterion("oper_user_name not between", value1, value2, "operUserName");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateIsNull() {
			addCriterion("oper_date is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateIsNotNull() {
			addCriterion("oper_date is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date =", value, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date <>", value, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateGreaterThan(Date value) {
			addCriterionForJDBCDate("oper_date >", value, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date >=", value, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateLessThan(Date value) {
			addCriterionForJDBCDate("oper_date <", value, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date <=", value, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateIn(List<Date> values) {
			addCriterionForJDBCDate("oper_date in", values, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("oper_date not in", values, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("oper_date between", value1, value2, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andOperDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("oper_date not between", value1, value2, "operDate");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsIsNull() {
			addCriterion("comments is null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsIsNotNull() {
			addCriterion("comments is not null");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsEqualTo(String value) {
			addCriterion("comments =", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsNotEqualTo(String value) {
			addCriterion("comments <>", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsGreaterThan(String value) {
			addCriterion("comments >", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsGreaterThanOrEqualTo(String value) {
			addCriterion("comments >=", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsLessThan(String value) {
			addCriterion("comments <", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsLessThanOrEqualTo(String value) {
			addCriterion("comments <=", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsLike(String value) {
			addCriterion("comments like", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsNotLike(String value) {
			addCriterion("comments not like", value, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsIn(List<String> values) {
			addCriterion("comments in", values, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsNotIn(List<String> values) {
			addCriterion("comments not in", values, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsBetween(String value1, String value2) {
			addCriterion("comments between", value1, value2, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andCommentsNotBetween(String value1, String value2) {
			addCriterion("comments not between", value1, value2, "comments");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogTypeEqualTo(Integer value) {
			addCriterion("log_type =", value, "logType");
			return (OperLogExample.Criteria) this;
		}

		public OperLogExample.Criteria andLogTypeNotEqualTo(Integer value) {
			addCriterion("log_type <>", value, "logType");
			return (OperLogExample.Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends OperLogExample.GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table t_s_oper_log
	 *
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}