package com.web.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 机房平面图管理业务查询条件类
 *
 * @author 田军兴
 * @date 2016-010-22
 */
public class RoomIcngphExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public RoomIcngphExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFloorNameIsNull() {
            addCriterion("floor_name is null");
            return (Criteria) this;
        }

        public Criteria andFloorNameIsNotNull() {
            addCriterion("floor_name is not null");
            return (Criteria) this;
        }

        public Criteria andFloorNameEqualTo(String value) {
            addCriterion("floor_name =", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameNotEqualTo(String value) {
            addCriterion("floor_name <>", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameGreaterThan(String value) {
            addCriterion("floor_name >", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameGreaterThanOrEqualTo(String value) {
            addCriterion("floor_name >=", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameLessThan(String value) {
            addCriterion("floor_name <", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameLessThanOrEqualTo(String value) {
            addCriterion("floor_name <=", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameLike(String value) {
            addCriterion("floor_name like", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameNotLike(String value) {
            addCriterion("floor_name not like", value, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameIn(List<String> values) {
            addCriterion("floor_name in", values, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameNotIn(List<String> values) {
            addCriterion("floor_name not in", values, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameBetween(String value1, String value2) {
            addCriterion("floor_name between", value1, value2, "floorName");
            return (Criteria) this;
        }

        public Criteria andFloorNameNotBetween(String value1, String value2) {
            addCriterion("floor_name not between", value1, value2, "floorName");
            return (Criteria) this;
        }

        public Criteria andImageNameIsNull() {
            addCriterion("image_name is null");
            return (Criteria) this;
        }

        public Criteria andImageNameIsNotNull() {
            addCriterion("image_name is not null");
            return (Criteria) this;
        }

        public Criteria andImageNameEqualTo(String value) {
            addCriterion("image_name =", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameNotEqualTo(String value) {
            addCriterion("image_name <>", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameGreaterThan(String value) {
            addCriterion("image_name >", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameGreaterThanOrEqualTo(String value) {
            addCriterion("image_name >=", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameLessThan(String value) {
            addCriterion("image_name <", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameLessThanOrEqualTo(String value) {
            addCriterion("image_name <=", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameLike(String value) {
            addCriterion("image_name like", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameNotLike(String value) {
            addCriterion("image_name not like", value, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameIn(List<String> values) {
            addCriterion("image_name in", values, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameNotIn(List<String> values) {
            addCriterion("image_name not in", values, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameBetween(String value1, String value2) {
            addCriterion("image_name between", value1, value2, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageNameNotBetween(String value1, String value2) {
            addCriterion("image_name not between", value1, value2, "imageName");
            return (Criteria) this;
        }

        public Criteria andImageRealPathIsNull() {
            addCriterion("image_real_path is null");
            return (Criteria) this;
        }

        public Criteria andImageRealPathIsNotNull() {
            addCriterion("image_real_path is not null");
            return (Criteria) this;
        }

        public Criteria andImageRealPathEqualTo(String value) {
            addCriterion("image_real_path =", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathNotEqualTo(String value) {
            addCriterion("image_real_path <>", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathGreaterThan(String value) {
            addCriterion("image_real_path >", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("image_real_path >=", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathLessThan(String value) {
            addCriterion("image_real_path <", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathLessThanOrEqualTo(String value) {
            addCriterion("image_real_path <=", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathLike(String value) {
            addCriterion("image_real_path like", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathNotLike(String value) {
            addCriterion("image_real_path not like", value, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathIn(List<String> values) {
            addCriterion("image_real_path in", values, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathNotIn(List<String> values) {
            addCriterion("image_real_path not in", values, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathBetween(String value1, String value2) {
            addCriterion("image_real_path between", value1, value2, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andImageRealPathNotBetween(String value1, String value2) {
            addCriterion("image_real_path not between", value1, value2, "imageRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonNameIsNull() {
            addCriterion("json_name is null");
            return (Criteria) this;
        }

        public Criteria andJsonNameIsNotNull() {
            addCriterion("json_name is not null");
            return (Criteria) this;
        }

        public Criteria andJsonNameEqualTo(String value) {
            addCriterion("json_name =", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameNotEqualTo(String value) {
            addCriterion("json_name <>", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameGreaterThan(String value) {
            addCriterion("json_name >", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameGreaterThanOrEqualTo(String value) {
            addCriterion("json_name >=", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameLessThan(String value) {
            addCriterion("json_name <", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameLessThanOrEqualTo(String value) {
            addCriterion("json_name <=", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameLike(String value) {
            addCriterion("json_name like", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameNotLike(String value) {
            addCriterion("json_name not like", value, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameIn(List<String> values) {
            addCriterion("json_name in", values, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameNotIn(List<String> values) {
            addCriterion("json_name not in", values, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameBetween(String value1, String value2) {
            addCriterion("json_name between", value1, value2, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonNameNotBetween(String value1, String value2) {
            addCriterion("json_name not between", value1, value2, "jsonName");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathIsNull() {
            addCriterion("json_real_path is null");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathIsNotNull() {
            addCriterion("json_real_path is not null");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathEqualTo(String value) {
            addCriterion("json_real_path =", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathNotEqualTo(String value) {
            addCriterion("json_real_path <>", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathGreaterThan(String value) {
            addCriterion("json_real_path >", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("json_real_path >=", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathLessThan(String value) {
            addCriterion("json_real_path <", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathLessThanOrEqualTo(String value) {
            addCriterion("json_real_path <=", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathLike(String value) {
            addCriterion("json_real_path like", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathNotLike(String value) {
            addCriterion("json_real_path not like", value, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathIn(List<String> values) {
            addCriterion("json_real_path in", values, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathNotIn(List<String> values) {
            addCriterion("json_real_path not in", values, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathBetween(String value1, String value2) {
            addCriterion("json_real_path between", value1, value2, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andJsonRealPathNotBetween(String value1, String value2) {
            addCriterion("json_real_path not between", value1, value2, "jsonRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlNameIsNull() {
            addCriterion("yml_name is null");
            return (Criteria) this;
        }

        public Criteria andYmlNameIsNotNull() {
            addCriterion("yml_name is not null");
            return (Criteria) this;
        }

        public Criteria andYmlNameEqualTo(String value) {
            addCriterion("yml_name =", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameNotEqualTo(String value) {
            addCriterion("yml_name <>", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameGreaterThan(String value) {
            addCriterion("yml_name >", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameGreaterThanOrEqualTo(String value) {
            addCriterion("yml_name >=", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameLessThan(String value) {
            addCriterion("yml_name <", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameLessThanOrEqualTo(String value) {
            addCriterion("yml_name <=", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameLike(String value) {
            addCriterion("yml_name like", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameNotLike(String value) {
            addCriterion("yml_name not like", value, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameIn(List<String> values) {
            addCriterion("yml_name in", values, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameNotIn(List<String> values) {
            addCriterion("yml_name not in", values, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameBetween(String value1, String value2) {
            addCriterion("yml_name between", value1, value2, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlNameNotBetween(String value1, String value2) {
            addCriterion("yml_name not between", value1, value2, "ymlName");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathIsNull() {
            addCriterion("yml_real_path is null");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathIsNotNull() {
            addCriterion("yml_real_path is not null");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathEqualTo(String value) {
            addCriterion("yml_real_path =", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathNotEqualTo(String value) {
            addCriterion("yml_real_path <>", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathGreaterThan(String value) {
            addCriterion("yml_real_path >", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("yml_real_path >=", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathLessThan(String value) {
            addCriterion("yml_real_path <", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathLessThanOrEqualTo(String value) {
            addCriterion("yml_real_path <=", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathLike(String value) {
            addCriterion("yml_real_path like", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathNotLike(String value) {
            addCriterion("yml_real_path not like", value, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathIn(List<String> values) {
            addCriterion("yml_real_path in", values, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathNotIn(List<String> values) {
            addCriterion("yml_real_path not in", values, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathBetween(String value1, String value2) {
            addCriterion("yml_real_path between", value1, value2, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andYmlRealPathNotBetween(String value1, String value2) {
            addCriterion("yml_real_path not between", value1, value2, "ymlRealPath");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
