package com.web.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 机房平面图管理业务查询条件类
 *
 * @author 田军兴
 * @date 2016-010-22
 */
public class RoomIcngphExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected List<RoomIcngphExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public RoomIcngphExample() {
        oredCriteria = new ArrayList<RoomIcngphExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public List<RoomIcngphExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void or(RoomIcngphExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public RoomIcngphExample.Criteria or() {
        RoomIcngphExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public RoomIcngphExample.Criteria createCriteria() {
        RoomIcngphExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected RoomIcngphExample.Criteria createCriteriaInternal() {
        RoomIcngphExample.Criteria criteria = new RoomIcngphExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<RoomIcngphExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<RoomIcngphExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<RoomIcngphExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<RoomIcngphExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new RoomIcngphExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new RoomIcngphExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new RoomIcngphExample.Criterion(condition, value1, value2));
        }

        public RoomIcngphExample.Criteria andIdIsNull() {
            addCriterion("id is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameIsNull() {
            addCriterion("floor_name is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameIsNotNull() {
            addCriterion("floor_name is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameEqualTo(String value) {
            addCriterion("floor_name =", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameNotEqualTo(String value) {
            addCriterion("floor_name <>", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameGreaterThan(String value) {
            addCriterion("floor_name >", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameGreaterThanOrEqualTo(String value) {
            addCriterion("floor_name >=", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameLessThan(String value) {
            addCriterion("floor_name <", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameLessThanOrEqualTo(String value) {
            addCriterion("floor_name <=", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameLike(String value) {
            addCriterion("floor_name like", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameNotLike(String value) {
            addCriterion("floor_name not like", value, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameIn(List<String> values) {
            addCriterion("floor_name in", values, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameNotIn(List<String> values) {
            addCriterion("floor_name not in", values, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameBetween(String value1, String value2) {
            addCriterion("floor_name between", value1, value2, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andFloorNameNotBetween(String value1, String value2) {
            addCriterion("floor_name not between", value1, value2, "floorName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameIsNull() {
            addCriterion("image_name is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameIsNotNull() {
            addCriterion("image_name is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameEqualTo(String value) {
            addCriterion("image_name =", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameNotEqualTo(String value) {
            addCriterion("image_name <>", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameGreaterThan(String value) {
            addCriterion("image_name >", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameGreaterThanOrEqualTo(String value) {
            addCriterion("image_name >=", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameLessThan(String value) {
            addCriterion("image_name <", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameLessThanOrEqualTo(String value) {
            addCriterion("image_name <=", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameLike(String value) {
            addCriterion("image_name like", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameNotLike(String value) {
            addCriterion("image_name not like", value, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameIn(List<String> values) {
            addCriterion("image_name in", values, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameNotIn(List<String> values) {
            addCriterion("image_name not in", values, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameBetween(String value1, String value2) {
            addCriterion("image_name between", value1, value2, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageNameNotBetween(String value1, String value2) {
            addCriterion("image_name not between", value1, value2, "imageName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathIsNull() {
            addCriterion("image_real_path is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathIsNotNull() {
            addCriterion("image_real_path is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathEqualTo(String value) {
            addCriterion("image_real_path =", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathNotEqualTo(String value) {
            addCriterion("image_real_path <>", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathGreaterThan(String value) {
            addCriterion("image_real_path >", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("image_real_path >=", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathLessThan(String value) {
            addCriterion("image_real_path <", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathLessThanOrEqualTo(String value) {
            addCriterion("image_real_path <=", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathLike(String value) {
            addCriterion("image_real_path like", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathNotLike(String value) {
            addCriterion("image_real_path not like", value, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathIn(List<String> values) {
            addCriterion("image_real_path in", values, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathNotIn(List<String> values) {
            addCriterion("image_real_path not in", values, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathBetween(String value1, String value2) {
            addCriterion("image_real_path between", value1, value2, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andImageRealPathNotBetween(String value1, String value2) {
            addCriterion("image_real_path not between", value1, value2, "imageRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameIsNull() {
            addCriterion("json_name is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameIsNotNull() {
            addCriterion("json_name is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameEqualTo(String value) {
            addCriterion("json_name =", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameNotEqualTo(String value) {
            addCriterion("json_name <>", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameGreaterThan(String value) {
            addCriterion("json_name >", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameGreaterThanOrEqualTo(String value) {
            addCriterion("json_name >=", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameLessThan(String value) {
            addCriterion("json_name <", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameLessThanOrEqualTo(String value) {
            addCriterion("json_name <=", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameLike(String value) {
            addCriterion("json_name like", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameNotLike(String value) {
            addCriterion("json_name not like", value, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameIn(List<String> values) {
            addCriterion("json_name in", values, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameNotIn(List<String> values) {
            addCriterion("json_name not in", values, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameBetween(String value1, String value2) {
            addCriterion("json_name between", value1, value2, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonNameNotBetween(String value1, String value2) {
            addCriterion("json_name not between", value1, value2, "jsonName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathIsNull() {
            addCriterion("json_real_path is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathIsNotNull() {
            addCriterion("json_real_path is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathEqualTo(String value) {
            addCriterion("json_real_path =", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathNotEqualTo(String value) {
            addCriterion("json_real_path <>", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathGreaterThan(String value) {
            addCriterion("json_real_path >", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("json_real_path >=", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathLessThan(String value) {
            addCriterion("json_real_path <", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathLessThanOrEqualTo(String value) {
            addCriterion("json_real_path <=", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathLike(String value) {
            addCriterion("json_real_path like", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathNotLike(String value) {
            addCriterion("json_real_path not like", value, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathIn(List<String> values) {
            addCriterion("json_real_path in", values, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathNotIn(List<String> values) {
            addCriterion("json_real_path not in", values, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathBetween(String value1, String value2) {
            addCriterion("json_real_path between", value1, value2, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andJsonRealPathNotBetween(String value1, String value2) {
            addCriterion("json_real_path not between", value1, value2, "jsonRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameIsNull() {
            addCriterion("yml_name is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameIsNotNull() {
            addCriterion("yml_name is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameEqualTo(String value) {
            addCriterion("yml_name =", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameNotEqualTo(String value) {
            addCriterion("yml_name <>", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameGreaterThan(String value) {
            addCriterion("yml_name >", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameGreaterThanOrEqualTo(String value) {
            addCriterion("yml_name >=", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameLessThan(String value) {
            addCriterion("yml_name <", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameLessThanOrEqualTo(String value) {
            addCriterion("yml_name <=", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameLike(String value) {
            addCriterion("yml_name like", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameNotLike(String value) {
            addCriterion("yml_name not like", value, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameIn(List<String> values) {
            addCriterion("yml_name in", values, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameNotIn(List<String> values) {
            addCriterion("yml_name not in", values, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameBetween(String value1, String value2) {
            addCriterion("yml_name between", value1, value2, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlNameNotBetween(String value1, String value2) {
            addCriterion("yml_name not between", value1, value2, "ymlName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathIsNull() {
            addCriterion("yml_real_path is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathIsNotNull() {
            addCriterion("yml_real_path is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathEqualTo(String value) {
            addCriterion("yml_real_path =", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathNotEqualTo(String value) {
            addCriterion("yml_real_path <>", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathGreaterThan(String value) {
            addCriterion("yml_real_path >", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("yml_real_path >=", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathLessThan(String value) {
            addCriterion("yml_real_path <", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathLessThanOrEqualTo(String value) {
            addCriterion("yml_real_path <=", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathLike(String value) {
            addCriterion("yml_real_path like", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathNotLike(String value) {
            addCriterion("yml_real_path not like", value, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathIn(List<String> values) {
            addCriterion("yml_real_path in", values, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathNotIn(List<String> values) {
            addCriterion("yml_real_path not in", values, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathBetween(String value1, String value2) {
            addCriterion("yml_real_path between", value1, value2, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andYmlRealPathNotBetween(String value1, String value2) {
            addCriterion("yml_real_path not between", value1, value2, "ymlRealPath");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }

        public RoomIcngphExample.Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (RoomIcngphExample.Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends RoomIcngphExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
