package com.web.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 机房平面图管理业务查询条件类
 *
 * @author 田军兴
 * @date 2016-010-22
 */
public class ServiceRoomIcngphExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected List<ServiceRoomIcngphExample.Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public ServiceRoomIcngphExample() {
        oredCriteria = new ArrayList<ServiceRoomIcngphExample.Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public List<ServiceRoomIcngphExample.Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void or(ServiceRoomIcngphExample.Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public ServiceRoomIcngphExample.Criteria or() {
        ServiceRoomIcngphExample.Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public ServiceRoomIcngphExample.Criteria createCriteria() {
        ServiceRoomIcngphExample.Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected ServiceRoomIcngphExample.Criteria createCriteriaInternal() {
        ServiceRoomIcngphExample.Criteria criteria = new ServiceRoomIcngphExample.Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<ServiceRoomIcngphExample.Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<ServiceRoomIcngphExample.Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<ServiceRoomIcngphExample.Criterion> getAllCriteria() {
            return criteria;
        }

        public List<ServiceRoomIcngphExample.Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new ServiceRoomIcngphExample.Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new ServiceRoomIcngphExample.Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new ServiceRoomIcngphExample.Criterion(condition, value1, value2));
        }

        public ServiceRoomIcngphExample.Criteria andIdIsNull() {
            addCriterion("id is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameIsNull() {
            addCriterion("floor_name is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameIsNotNull() {
            addCriterion("floor_name is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameEqualTo(String value) {
            addCriterion("floor_name =", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameNotEqualTo(String value) {
            addCriterion("floor_name <>", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameGreaterThan(String value) {
            addCriterion("floor_name >", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameGreaterThanOrEqualTo(String value) {
            addCriterion("floor_name >=", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameLessThan(String value) {
            addCriterion("floor_name <", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameLessThanOrEqualTo(String value) {
            addCriterion("floor_name <=", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameLike(String value) {
            addCriterion("floor_name like", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameNotLike(String value) {
            addCriterion("floor_name not like", value, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameIn(List<String> values) {
            addCriterion("floor_name in", values, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameNotIn(List<String> values) {
            addCriterion("floor_name not in", values, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameBetween(String value1, String value2) {
            addCriterion("floor_name between", value1, value2, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andFloorNameNotBetween(String value1, String value2) {
            addCriterion("floor_name not between", value1, value2, "floorName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameIsNull() {
            addCriterion("image_name is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameIsNotNull() {
            addCriterion("image_name is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameEqualTo(String value) {
            addCriterion("image_name =", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameNotEqualTo(String value) {
            addCriterion("image_name <>", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameGreaterThan(String value) {
            addCriterion("image_name >", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameGreaterThanOrEqualTo(String value) {
            addCriterion("image_name >=", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameLessThan(String value) {
            addCriterion("image_name <", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameLessThanOrEqualTo(String value) {
            addCriterion("image_name <=", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameLike(String value) {
            addCriterion("image_name like", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameNotLike(String value) {
            addCriterion("image_name not like", value, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameIn(List<String> values) {
            addCriterion("image_name in", values, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameNotIn(List<String> values) {
            addCriterion("image_name not in", values, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameBetween(String value1, String value2) {
            addCriterion("image_name between", value1, value2, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageNameNotBetween(String value1, String value2) {
            addCriterion("image_name not between", value1, value2, "imageName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathIsNull() {
            addCriterion("image_real_path is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathIsNotNull() {
            addCriterion("image_real_path is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathEqualTo(String value) {
            addCriterion("image_real_path =", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathNotEqualTo(String value) {
            addCriterion("image_real_path <>", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathGreaterThan(String value) {
            addCriterion("image_real_path >", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("image_real_path >=", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathLessThan(String value) {
            addCriterion("image_real_path <", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathLessThanOrEqualTo(String value) {
            addCriterion("image_real_path <=", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathLike(String value) {
            addCriterion("image_real_path like", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathNotLike(String value) {
            addCriterion("image_real_path not like", value, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathIn(List<String> values) {
            addCriterion("image_real_path in", values, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathNotIn(List<String> values) {
            addCriterion("image_real_path not in", values, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathBetween(String value1, String value2) {
            addCriterion("image_real_path between", value1, value2, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andImageRealPathNotBetween(String value1, String value2) {
            addCriterion("image_real_path not between", value1, value2, "imageRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameIsNull() {
            addCriterion("json_name is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameIsNotNull() {
            addCriterion("json_name is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameEqualTo(String value) {
            addCriterion("json_name =", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameNotEqualTo(String value) {
            addCriterion("json_name <>", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameGreaterThan(String value) {
            addCriterion("json_name >", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameGreaterThanOrEqualTo(String value) {
            addCriterion("json_name >=", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameLessThan(String value) {
            addCriterion("json_name <", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameLessThanOrEqualTo(String value) {
            addCriterion("json_name <=", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameLike(String value) {
            addCriterion("json_name like", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameNotLike(String value) {
            addCriterion("json_name not like", value, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameIn(List<String> values) {
            addCriterion("json_name in", values, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameNotIn(List<String> values) {
            addCriterion("json_name not in", values, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameBetween(String value1, String value2) {
            addCriterion("json_name between", value1, value2, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonNameNotBetween(String value1, String value2) {
            addCriterion("json_name not between", value1, value2, "jsonName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathIsNull() {
            addCriterion("json_real_path is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathIsNotNull() {
            addCriterion("json_real_path is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathEqualTo(String value) {
            addCriterion("json_real_path =", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathNotEqualTo(String value) {
            addCriterion("json_real_path <>", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathGreaterThan(String value) {
            addCriterion("json_real_path >", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("json_real_path >=", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathLessThan(String value) {
            addCriterion("json_real_path <", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathLessThanOrEqualTo(String value) {
            addCriterion("json_real_path <=", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathLike(String value) {
            addCriterion("json_real_path like", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathNotLike(String value) {
            addCriterion("json_real_path not like", value, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathIn(List<String> values) {
            addCriterion("json_real_path in", values, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathNotIn(List<String> values) {
            addCriterion("json_real_path not in", values, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathBetween(String value1, String value2) {
            addCriterion("json_real_path between", value1, value2, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andJsonRealPathNotBetween(String value1, String value2) {
            addCriterion("json_real_path not between", value1, value2, "jsonRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameIsNull() {
            addCriterion("yml_name is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameIsNotNull() {
            addCriterion("yml_name is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameEqualTo(String value) {
            addCriterion("yml_name =", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameNotEqualTo(String value) {
            addCriterion("yml_name <>", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameGreaterThan(String value) {
            addCriterion("yml_name >", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameGreaterThanOrEqualTo(String value) {
            addCriterion("yml_name >=", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameLessThan(String value) {
            addCriterion("yml_name <", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameLessThanOrEqualTo(String value) {
            addCriterion("yml_name <=", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameLike(String value) {
            addCriterion("yml_name like", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameNotLike(String value) {
            addCriterion("yml_name not like", value, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameIn(List<String> values) {
            addCriterion("yml_name in", values, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameNotIn(List<String> values) {
            addCriterion("yml_name not in", values, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameBetween(String value1, String value2) {
            addCriterion("yml_name between", value1, value2, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlNameNotBetween(String value1, String value2) {
            addCriterion("yml_name not between", value1, value2, "ymlName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathIsNull() {
            addCriterion("yml_real_path is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathIsNotNull() {
            addCriterion("yml_real_path is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathEqualTo(String value) {
            addCriterion("yml_real_path =", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathNotEqualTo(String value) {
            addCriterion("yml_real_path <>", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathGreaterThan(String value) {
            addCriterion("yml_real_path >", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathGreaterThanOrEqualTo(String value) {
            addCriterion("yml_real_path >=", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathLessThan(String value) {
            addCriterion("yml_real_path <", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathLessThanOrEqualTo(String value) {
            addCriterion("yml_real_path <=", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathLike(String value) {
            addCriterion("yml_real_path like", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathNotLike(String value) {
            addCriterion("yml_real_path not like", value, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathIn(List<String> values) {
            addCriterion("yml_real_path in", values, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathNotIn(List<String> values) {
            addCriterion("yml_real_path not in", values, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathBetween(String value1, String value2) {
            addCriterion("yml_real_path between", value1, value2, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andYmlRealPathNotBetween(String value1, String value2) {
            addCriterion("yml_real_path not between", value1, value2, "ymlRealPath");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }

        public ServiceRoomIcngphExample.Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (ServiceRoomIcngphExample.Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends ServiceRoomIcngphExample.GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_b_service_room_icngph
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
