package com.web.entity;

import java.util.Date;

import com.web.core.entity.BaseEntity;

/**
 * 机柜管理实体类
 *
 * @author 田军兴
 * @date 2016-11-6
 */
public class Cabinet extends BaseEntity {

	/**
	 * 名称
	 */
	private String name;

	/**
	 * 资产编号
	 */
	private String resourceCode;

	/**
	 * 机房ID
	 */
	private String roomId;

	/**
	 * 设备类型
	 */
	private String equipmentTypeId;

	/**
	 * 所属机房区域id
	 */
	private String areaId;

	/**
	 * 所处坐标x
	 */
	private Float x;

	/**
	 * 所处坐标y
	 */
	private Float y;

	/**
	 * 所处坐标z
	 */
	private Float z;

	/**
	 * 高度 U
	 */
	private Integer height;

	/**
	 * 重量 kg
	 */
	private Float weight;

	/**
	 * 分配的额定功率
	 */
	private Float power;

	/**
	 * This field was generated by MyBatis Generator.
	 */
	private Integer roomStatus;

	/**
	 * 模型高度
	 */
	private Integer modelHeight;

	/**
	 * 模型宽度
	 */
	private Integer modelWidth;

	/**
	 * 模型颜色
	 */
	private String modelColor;

	/**
	 * 状态
	 */
	private Integer status;

	/**
	 * 保修时间
	 */
	private Date warrantyTime;

	/**
	 * 投运时间
	 */
	private Date workTime;

	/**
	 * 机柜u位顺序：0是从下向上，1反之
	 */
	private Integer uOrder;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getResourceCode() {
		return resourceCode;
	}

	public void setResourceCode(String resourceCode) {
		this.resourceCode = resourceCode;
	}

	public String getEquipmentTypeId() {
		return equipmentTypeId;
	}

	public void setEquipmentTypeId(String equipmentTypeId) {
		this.equipmentTypeId = equipmentTypeId;
	}

	public String getAreaId() {
		return areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public Float getX() {
		return x;
	}

	public void setX(Float x) {
		this.x = x;
	}

	public Float getY() {
		return y;
	}

	public void setY(Float y) {
		this.y = y;
	}

	public Float getZ() {
		return z;
	}

	public void setZ(Float z) {
		this.z = z;
	}

	public Integer getHeight() {
		return height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Float getWeight() {
		return weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public Float getPower() {
		return power;
	}

	public void setPower(Float power) {
		this.power = power;
	}

	public Integer getRoomStatus() {
		return roomStatus;
	}

	public void setRoomStatus(Integer roomStatus) {
		this.roomStatus = roomStatus;
	}

	public Integer getModelHeight() {
		return modelHeight;
	}

	public void setModelHeight(Integer modelHeight) {
		this.modelHeight = modelHeight;
	}

	public Integer getModelWidth() {
		return modelWidth;
	}

	public void setModelWidth(Integer modelWidth) {
		this.modelWidth = modelWidth;
	}

	public String getModelColor() {
		return modelColor;
	}

	public void setModelColor(String modelColor) {
		this.modelColor = modelColor;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getWarrantyTime() {
		return warrantyTime;
	}

	public void setWarrantyTime(Date warrantyTime) {
		this.warrantyTime = warrantyTime;
	}

	public Date getWorkTime() {
		return workTime;
	}

	public void setWorkTime(Date workTime) {
		this.workTime = workTime;
	}

	public Integer getuOrder() {
		return uOrder;
	}

	public void setuOrder(Integer uOrder) {
		this.uOrder = uOrder;
	}

	public String getRoomId() {
		return roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

}